# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.6

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pip3 install category-encoders==2.1.0 cython==0.29.10 --install-option="--no-cython-compile" distlib==0.3.1 Flask==1.1.1
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            pytest MachineLearning/tests/test_controller.py